# Generated by Django 5.0.2 on 2024-03-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_vendedor_venta_remove_cliente_fechacumpleaños'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
