# Generated by Django 5.0.2 on 2024-03-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_pantalon_remera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticulo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('talle', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
