# Generated by Django 5.0.2 on 2024-03-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_pantalon_categoria_alter_pantalon_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantalon',
            old_name='nombreArticulo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='remera',
            old_name='nombreArticulo',
            new_name='articulo',
        ),
        migrations.RemoveField(
            model_name='buzo',
            name='nombreArticulo',
        ),
        migrations.AddField(
            model_name='buzo',
            name='articulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buzo',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buzo',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buzo',
            name='talle',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
